var appConstants = {
  ADD_TALKING_POINT: 'ADD_TALKING_POINT',
  REMOVE_TALKING_POINT: 'REMOVE_TALKING_POINT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  CHANGE_EVENT: 'CHANGE'
};
module.exports = appConstants;
