var appConstants = {
  ADD_TALKING_POINT: 'ADD_TALKING_POINT',
  REMOVE_TALKING_POINT: 'REMOVE_TALKING_POINT',
  HIGHLIGHT_TALKING_POINT: 'HIGHLIGHT_TALKING_POINT',
  CLEAR_TALKING_POINT_HIGHLIGHT: 'CLEAR_TALKING_POINT_HIGHLIGHT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  CHANGE_EVENT: 'CHANGE'
};
module.exports = appConstants;
